### PR TITLE
added debugging header and blocking for specific pages

### PR DESCRIPTION
**Pull request by virgil**
(1) Adding http response header X-Onion-Url that has helped me as well as onion-site operators debug their site.

(2) Unsure what happened to the blocking of specific pages, but I added it back.  I've needed this a few times.  It blocks by the onion-url and doesn't care whether it's via http or https.

### CODE REVIEW

**Comment by evilaliv3** [comment]
@virgil is this the latest patch you were interested in me to check it?

my comments are the following:
1) X-Onion-Url: i think probably it's better to use the X-Tor2web header adding some variables to it like onion:antani.onion
2) for the block for specific pages i removed it since a few cause we were not using it and this implementation causes the following problems: every request need 2 hash checks (not so big problem but having multiple separated lists would solve the issue.

let's think a little about this and if we want to implement also other things like keeping a counter for the matched urls in order be able to remove entries not matched since a few (and this would probably require some db support like e.g. a simple sqlite thing)

\cc @fpietrosanti

**Comment by virgil** [comment]
@evilaliv3, look at the next patch ;)

1) sounds fine to me.
2) I currently run the most trafficed tor2web install and the CPU load with two hashes is neglible.  I rarely exceed 15% CPU.

**Comment by evilaliv3** [comment]
@virgil io do not see any more recent patch than this.

**Comment by virgil** [comment]
For what it's worth the the X-Onion-Url in the HTTP Request has still been helpful to be in debugging problems.  Still recommend including.

**Pull request closed without merging**
